### ISSUE TITLE
EPIC - rename ansible roles in order to create a gallaxy collection

### ISSUE THREAD

**Issue by rayashworth** [IBM/community-automation#83]
List of roles that need to be renamed with '_' instead of '-' in role name

Check off as completed.
- [x] aws-cli-install
- [x] aws-route53
- [x] azure-cli-install
- [x] common-services
- [x] common-services-cat-src-inst
- [x] csi-cephfs-fyre
- [x] deploy-ova-vmware
- [x] git-install-fyre
- [x] google-cli-install
- [x] oc-client-install
- [x] ocp-cluster-tag
- [x] ocp-login
- [x] provision-ocp-cluster
- [x] python-install-fyre
- [x] recover-epxired-certificates
- [x] recover-machine-config
- [x] request-ocp-aws
- [x] request-ocp-fyre
- [x] request-ocp-roks
- [x] request-ocp4-logging
- [x] request-ocpplus-cluster-transfer-fyre
- [x] request-ocs
- [x] request-ocs-local-storage
- [x] start-aws-cluster
- [x] stop-aws-cluster
